name:                inventory
version:             0.1.0.0
github:              "aaronallen8455/inventory"
license:             BSD3
author:              "Aaron Allen"
maintainer:          "aaronallen8455@gmail.com"
copyright:           "2021 Aaron Allen"
tested-with: ghc ==8.8.4 ghc ==8.10.3

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aaronallen8455/inventory#readme>

dependencies:
- base             >= 4.7 && < 5
- appendmap        >= 0.1.5 && < 0.2
- containers       >= 0.6.2 && < 0.7
- bytestring       >= 0.10.12 && < 0.11
- directory        >= 1.3.6 && < 1.4
- filepath         >= 1.4.2 && < 1.5
- ghc              >= 8.8
- ghc-paths        >= 0.1.0 && < 0.2
- mtl              >= 2.2.2 && < 2.3

ghc-options: -Wall
             -fwarn-incomplete-patterns

library:
  source-dirs: src

executables:
  inventory:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-A16m
    dependencies:
    - inventory

tests:
  inventory-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwrite-ide-info
    - -hiedir=test/hie
    dependencies:
    - inventory
    - tasty
    - tasty-hunit
